# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eec1c06ba8fef9a17e3e2e5adb2819ff567135451a2981e9710166a4de082bfe2ddde08638478c0056b7231292542049f63c3dd5c5be226ade519802f30a8ac

test:
  secret_key_base: ba7096e7e21b76215b75a8eb86aabdb0fb095dd0f2b3479a3c64fa8e5e4bea152f707a42906b36bf2a32b607fa7e5bc7bd0092793ed7904972a2b8673cca8a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
